# -*- coding: utf-8 -*-
"""Project_2_Level_1_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XK8cCelTwPSglo5D2e-s6eZFCTWoHRMl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/ifood_df.csv')
df

df.isnull().sum()

df.duplicated().sum()

df.info()

df['totalMnt'] = df['MntWines']+df['MntFruits']+df['MntMeatProducts']+df['MntFishProducts']+df['MntSweetProducts']+df['MntGoldProds']
df['total_purchases'] = df['NumDealsPurchases']+df['NumWebPurchases']+df['NumCatalogPurchases']+df['NumStorePurchases']

# # Descriptive Statistics: Calculate key metrics such as average purchase value, frequency of purchases, etc.

Average_Purchases = df['totalMnt'].mean()
print('Average_Purchases :',Average_Purchases)

frequency_Purchases = df['total_purchases'].mean()
print('frequency Purchases :',frequency_Purchases)

# Customer Segmentation: Utilize clustering algorithms (e.g., K-means) to segment customers based on behavior and purchase patterns.

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
temp = df[['Income','Age','NumWebVisitsMonth','totalMnt','total_purchases','NumWebVisitsMonth']]
scaler = StandardScaler()
temp_scaled = scaler.fit_transform(temp)

# apply kmeans clustring

kmeans = KMeans(n_clusters=4,random_state=42)
df['cluster'] = kmeans.fit_predict(temp_scaled)

df['cluster'].value_counts()

# visualizations

# Scatterplot
plt.figure(figsize=(9,6))
sns.scatterplot(x='Income',y='totalMnt',hue='cluster',data=df,palette="deep")
plt.title('total MNT vs Income')
plt.show()

plt.figure(figsize=(9,6))
sns.countplot(x='cluster',data=df,hue = 'cluster',palette="deep")
plt.title('Customer in each cluster')
plt.show()

cluster_anaylsis = df.groupby('cluster').mean()[['Income','Age','NumWebVisitsMonth','totalMnt','total_purchases','NumWebVisitsMonth','Recency']]
print('cluster Analysis :',cluster_anaylsis)