# -*- coding: utf-8 -*-
"""oasis infobyte_project_2_Lavel_2_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvFuxpqZdd_Xc2y6_Y2azSZjiG5x7jlP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/WineQT.csv')
df

df.isnull().sum()

df.duplicated().sum()

df.info()

df.describe()

plt.figure(figsize=(12,6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

x = df.drop(columns=['quality','Id'],axis=1)
y = df['quality']

x.head()

y.head()

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=42)

X_train

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

models= {
    "Random Forest": RandomForestClassifier(random_state=42),
    "SGD Classifier": SGDClassifier(random_state=42),
    "SVC": SVC(random_state=42)
}

for model_name, model in models.items():
  model.fit(X_train_scaled,Y_train)
  y_pred = model.predict(X_test_scaled)
  print('model name :',model_name)
  print('Classification_report :\n',classification_report(Y_test, y_pred))
  print(f"Accuracy:\n",{accuracy_score(Y_test, y_pred)})
