# -*- coding: utf-8 -*-
"""project_5_Level_2_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvFuxpqZdd_Xc2y6_Y2azSZjiG5x7jlP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df = pd.read_csv('/content/creditcard.csv')
df

df.info()

df.isnull().sum()

class_counts = df['Class'].value_counts()
class_counts

plt.figure(figsize=(6, 4))
sns.barplot(x=class_counts.index, y=class_counts.values, palette="coolwarm")
plt.title("Class Distribution")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

# Normalize column Amount

df['Amount'] = (df['Amount'] - df['Amount'].mean()) / df['Amount'].std()

x = df.drop(columns=['Class'],axis=1)
y = df['Class']

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=42)

X_train

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled =scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score, roc_curve, confusion_matrix

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_scaled, Y_train)

y_pred = rf.predict(X_test_scaled)
y_prob = rf.predict_proba(X_test_scaled)[:, 1]

print("Classification Report:\n", classification_report(Y_test, y_pred))
roc_auc = roc_auc_score(Y_test, y_prob)
print("ROC AUC Score:", roc_auc)

