# -*- coding: utf-8 -*-
"""Project_1_Level_1_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XK8cCelTwPSglo5D2e-s6eZFCTWoHRMl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/retail_sales_dataset.csv')
df

df.isnull().sum()

df.duplicated().sum()

df.info()

df['Date']=pd.to_datetime(df['Date'])

df.info()

df.describe()

df[['Gender','Product Category']].mode()

avg_sales_per_customer = df.groupby('Customer ID')['Total Amount'].mean()
print('average_sales_per_customer:\n',avg_sales_per_customer)

sales_by_categories = df.groupby('Product Category')['Total Amount'].sum()
print('sales_by_categories:\n',sales_by_categories)

# Vsualialization
# Bar Chart : sales by product category

plt.figure(figsize=(12,6))
sales_by_categories.plot(kind='bar')
plt.title('sales by product category')
plt.xlabel('product category')
plt.ylabel('total sales')
plt.show()

df.set_index('Date',inplace=True)

# sales trends over time

sales_trends = df['Total Amount'].resample('m').sum()
print(sales_trends)

plt.figure(figsize=(12,6))
plt.plot(sales_trends,marker='o',linestyle='-')
plt.title('Monthly sales trends')
plt.xlabel('Date')
plt.ylabel('Total amounts')
plt.show()

# customers and product anaylises

age_gender_sales =df.groupby(['Gender','Age'])['Total Amount'].sum().unstack()
print('sales by gender and age:\n',age_gender_sales)

top_customers = df.groupby('Customer ID')['Total Amount'].sum().sort_values(ascending=False).head(10)
print('top 10 customers:\n',top_customers)

best_selling_products = df.groupby('Product Category')['Quantity'].sum().sort_values(ascending=False)
print('best selling products:\n',best_selling_products)

# Vsualialization
# heatmap : correlation between numerical columns

plt.figure(figsize=(12,6))
numerical_columns = df.select_dtypes('int64')
sns.heatmap(numerical_columns.corr(),annot=True,cmap='coolwarm')
plt.title('correlation heatmap')
plt.show()

"""# **Recommenndation**

most frequent product category is cloting

most frequent gender is female

product categorical highiest sale

1.   Clothing = 155580
2.   Electrocins = 156905

in year 01-2024 sales trends is decreses
"""