# -*- coding: utf-8 -*-
"""project_4_Level_2_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvFuxpqZdd_Xc2y6_Y2azSZjiG5x7jlP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df1 = pd.read_csv('/content/apps.csv.zip')
df1

df2 = pd.read_csv('/content/user_reviews.csv.zip')
df2

df1.info()
df2.info()

df1['Installs'] = df1['Installs'].str.replace("[+,]", "", regex=True).astype(int)

df1['Price'] = df1['Price'].str.replace("[$,]", "", regex=True).astype(float)

df1.info()

df1.fillna({'Rating': df1['Rating'].median(), 'Size': df1['Size'].median()}, inplace=True)

df1['Last Updated'] = pd.to_datetime(df1['Last Updated'])

category_counts = df1['Category'].value_counts()

plt.figure(figsize=(12, 6))
sns.barplot(x=category_counts.values, y=category_counts.index)
plt.title("App Distribution Across Categories")
plt.xlabel("Number of Apps")
plt.ylabel("Categories")
plt.show()

sentiment_summary = df2['Sentiment'].value_counts()

plt.figure(figsize=(8, 4))
sns.barplot(x=sentiment_summary.index, y=sentiment_summary.values)
plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.show()

fig = px.scatter(df1, x='Rating', y='Installs', color='Category', size='Reviews',title="Rating vs Installs with Reviews")
fig.show()

fig2 = px.histogram(df2, x="Sentiment_Polarity", color="Sentiment", marginal="rug",title="Sentiment Polarity Distribution")
fig2.show()